# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12u4TBcVJsHFstMLykmGhoeoqWkEEscEV
"""

s=1
print(type(s))
a="hello"
print(type(a))
b=[1,2]
print(type(b))
c={1:'apple',2:'orange'}
print(type(c))
d=True
print(type(d))
e=1.2
print(type(e))
f={"a","b"}
print(type(f))
g=()
print(type(g))
h=bytes()
print(type(h))
i=bytearray()
print(type(i))
j=range(4)
print(type(j))